// Json Mapping Automatically Generated By JsonToolkit Library for C#
// Diego Trinciarelli 2011
// To use this code you will need to reference Newtonsoft's Json Parser, downloadable from codeplex.
// http://json.codeplex.com/
// 

using Newtonsoft.Json;

namespace MusicLogicWp7
{

    
    public class HybridResult
    {

        public Values Values;
        public int Code;

        //Empty Constructor
        public HybridResult() { }

        public string Serialize()
        {
            return JsonConvert.SerializeObject(this);
        }
        public static HybridResult FromJson(string json)
        {
            return JsonConvert.DeserializeObject<HybridResult>(json);
        }
    }



    public class Song
    {

        //public string Name;
        //public string Language;
        //public int Id;
        //public int Duration;
        //public object Desc;
        //public string ArtistName;
        //public long AlbumId;
        //public long ArtistId;
        //public int LyricId;
        //public string AlbumName;
        //public bool Liked;
        public string Mp3;
        //public int AlbumIndex;
        //public string BigCover;
        //public string NormalCover;
        //public string TinyCover;
        //public string SmallCover;

        //Empty Constructor
        public Song() { }

    }



    public class Values
    {

        public Song[] Songs;

        //Empty Constructor
        public Values() { }

    }

}
//Json Mapping End
